"""
Django settings for portingPTRIoT project.

Generated by 'django-admin startproject' using Django 2.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
# WARNING: change the BASE_DIR to '/var/www/...' after finished developing on
# localhost
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
#BASE_DIR = '/var/www/Porting-PTRIoT/'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'nef9g$pdz^3z9pz6ofld=d0y(9yq&njd8o250b1!!2!u2*hb)-'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# WARNING: change the ALLOWED_HOSTS to '3.0.184.42' after finished developing on
# localhost
#ALLOWED_HOSTS = ['3.0.184.42','localhost']
ALLOWED_HOSTS = ['104.198.255.60','35.222.220.166','localhost','127.0.0.1','10.110.128.26']


# Application definition

INSTALLED_APPS = [
    'pydash',
    'django.contrib.admin',
    'welcome.apps.WelcomeConfig', #Manually added
    'accounts.apps.AccountsConfig', #Manually added
    'userdashboard.apps.UserdashboardConfig', #Manually added
    'dataanalytics.apps.DataanalyticsConfig', #Manually added
    'gateway.apps.GatewayConfig', #Manually added
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'portingPTRIoT.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        #'DIRS': ['portingPTRIoT/templates'],
        'DIRS': [os.path.join(BASE_DIR, 'portingPTRIoT/templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'portingPTRIoT.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases
# WARNING! Change this from local when committing!
DB_ADDR = 'dbdashboard'
DB_PORT = '27017'
DB_NAME = 'web_service'
DB_USER = 'admindbtest'
DB_PASS = 'pFkg52L7Bffkdt95'

GTW_HOST = "10.111.209.201"
GTW_PORT = "8000"

HRA_HOST = "10.106.104.92"
HRA_PORT = "8000"

ECG_HOST = ""
ECG_PORT = ""

DATABASES = {
    'default': {
        'ENGINE': 'djongo',
        'NAME': DB_NAME,
        #'HOST':'mongodb://admindbtest:pFkg52L7Bffkdt95@18.140.63.5:27017/test_database',
        'HOST':'mongodb://'+DB_ADDR+':'+DB_PORT+'/'+DB_NAME,
    }
}
# 18.140.72.21


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'portingPTRIoT/static/')
]
STATIC_ROOT = os.path.join(BASE_DIR, 'static/')
STATIC_URL = '/static/'

# For Emailing account veriyfications
#EMAIL_USE_TLS = True
EMAIL_USE_SSL = True
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'abd.jaahiduddin@gmail.com'
EMAIL_HOST_PASSWORD = '1sadwd0'
#EMAIL_PORT = 587
EMAIL_PORT = 465

# To use custom user model
AUTH_USER_MODEL = 'accounts.CustomUser'

