# Generated by Django 2.2.4 on 2019-08-21 08:05

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190819_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='package',
            field=models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum')], default='bronze', max_length=2),
        ),
        migrations.AddField(
            model_name='customuser',
            name='topic',
            field=jsonfield.fields.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
