# Generated by Django 2.2.4 on 2019-08-28 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190828_0305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='body_height',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='body_weight',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='devicemac',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
