# Generated by Django 2.2.4 on 2019-09-05 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20190905_0342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='devicemac',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
