# Generated by Django 2.2.4 on 2019-09-05 04:10

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20190905_0352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='devicemac',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
