# Generated by Django 2.2.4 on 2019-09-05 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20190905_1426'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='devicemacs',
            new_name='topics_devicemacs_jwts',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='topics',
        ),
    ]
