# Generated by Django 2.2.4 on 2019-09-05 14:34

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20190905_1431'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='topics_devicemacs_jwts',
            new_name='devicemacs',
        ),
        migrations.AddField(
            model_name='customuser',
            name='topics',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
