# Generated by Django 2.2.4 on 2019-09-05 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20190905_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='topics',
        ),
    ]
