# Generated by Django 2.2.4 on 2019-09-05 14:42

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_customuser_topics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='topics',
            field=jsonfield.fields.JSONField(default={}),
        ),
    ]
