# Generated by Django 2.2.4 on 2019-09-05 15:08

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_remove_customuser_topics'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='topics',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
