# Generated by Django 2.2.4 on 2019-09-05 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_auto_20190905_1511'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='devicemac',
            new_name='devicemacs',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='topic',
            new_name='topics',
        ),
    ]
