# Generated by Django 2.2.4 on 2019-09-05 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_customuser_device'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='device',
            new_name='devicemacs',
        ),
    ]
